on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

name: twitter-archive

jobs:
  twitter-archive-scrape:
    
    runs-on: ubuntu-latest
    
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
      TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
    
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          persist-credentials: false
          fetch-depth: 0
      
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          use-public-rspm: true
      
      - uses: r-lib/actions/setup-r-dependencies@v2
      
      - name: 'scrape new data'
        run: |
          git config --local user.email "didactic.fortnight@gmail.com"
          git config --local user.name "Jake Thompson"
          Rscript scrape-twitter-data.R
      
      - name: 'push commits'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: 'true'
          branch: 'main'
